### ISSUE TITLE
Questions about the comparison with Gigahorse

### ISSUE THREAD

**Issue by sifislag** [SeUniVr/EtherSolve_ICPC2021_ReplicationPackage#1]
Hi,

Congratulations on your paper! 
I'm part of the team working on the [gigahorse decompiler](https://github.com/nevillegrech/gigahorse-toolchain).
We're constantly improving gigahorse and are interested in comparing it against other tools to improve our results if needed.

I have a few questions about how you compared EtherSolve with gigahorse so we can perform the comparison using different versions of it:
*  Which version of gigahorse did you use?
*  Do you have the scripts to postprocess the output of gigahorse to get your IR and make the comparison of the outputs?

Thanks,
Sifis.

**Comment by VersusF** [comment]
Hello.
Sorry for the late response but I did not receive the email and i noticed your issue a few days ago.

The Gigahorse version that we used was the master branch cloned on 8th November 2020. We ran it in a docker container based on ubuntu bionic.
The commands that we used are:
- `apt update; apt upgrade`
- `apt install libboost-all-dev`
- `apt install python3.8`
- `apt install wget`
- `wget https://github.com/souffle-lang/souffle/releases/download/2.0.2/souffle_2.0.2-1_amd64.deb`
- `dpkg -i souffle_2.0.2-1_amd64.deb`
- `apt install -f`
- `dpkg -i souffle_2.0.2-1_amd64.deb`
- `apt install git`
- `git clone https://github.com/nevillegrech/gigahorse-toolchain.git --recursive`
- `cd gigahorse-toolchain`
- `cd souffle-addon`
- `make`
- `apt install graphviz`
- `apt install python3-pip`
- `python3.8 -m pip install pydot`
- `apt install vim` and modify the first line of `gigahorse.py` to execute it with python3.8

The script used to translate the Gigahorse representation into our intermediate representation is the following
```python
import csv
import json
import os
from pathlib import Path

SOURCE_CSV = 'dataset.csv'
OUTPUT_FOLDER_IR = 'outputs/gigahorse_ir/'
OUTPUT_FOLDER_GIGAHORSE_REPRESENTATION = 'outputs/gigahorse_representation/'
START_INDEX = 1 # Default: 1
END_INDEX = 1001 # Default: 1001


def remove_x0(s):
    return s.split('0x')[0]
    # return s.split('x')[-1]
    # return s.replace('x','')

def translate_node(node, translation_dict):
    return translation_dict[node] if node in translation_dict else node

def build_cfg(address):
    filename = OUTPUT_FOLDER_GIGAHORSE_REPRESENTATION + 'Contract_' + address + '.evm'

    if not os.path.isfile(filename + '.out'): #os.stat(filename + '.info').st_size + os.stat(filename  + '.local.info').st_size != 0 or not os.path.isfile(filename + '.out'):
        return {
            'nodes': [],
            'edges': [],
            'timeMillis': 0 
        }

    nodes = []
    edges = []
    translation_dict = {}
    with open(filename + '.out', 'r') as f:
        block_offset = None
        for line in f:
            if line.startswith('Begin block'):
                block_offset = int(remove_x0(line.strip().split(' ')[-1][2:]), 16)
            if line.startswith('prev'):
                succs = line.strip().split('{')[2].split('}')[0]
                if (len(succs) != 0):
                    succs = succs.split(',')
                    succs = map(lambda x: int(remove_x0(x.strip()[3:-1]), 16), succs)
                    for succ in succs:
                        edges.append([block_offset, succ])
                nodes.append(block_offset)
            if 'CALLPRIVATE' in line:
                # 0x23a1: CALLPRIVATE v23a0(0x230)
                # 0x1c5e: v1c5e_0, v1c5e_1, v1c5e_2 = CALLPRIVATE v1c5b(0x1e97) v1c58(0x1c5f)
                target = int(remove_x0(line.split('(')[1].split(')')[0][2:]), 16)
                translation_dict[block_offset] = target
    
    nodes = list(map(lambda node : translate_node(node, translation_dict), nodes))
    edges = list(map(lambda edge : [translate_node(edge[0], translation_dict), translate_node(edge[1], translation_dict)], edges))

    return {
        'nodes': nodes,
        'edges': edges,
        'timeMillis': 0
    }


if __name__ == "__main__":
    Path(OUTPUT_FOLDER_IR).mkdir(exist_ok=True, parents=True)
    Path(OUTPUT_FOLDER_GIGAHORSE_REPRESENTATION).mkdir(exist_ok=True, parents=True)
    Path('tmp/').mkdir(exist_ok=True, parents=True)
    with open(SOURCE_CSV, 'r') as fi:
        reader = csv.DictReader(fi)
        counter = 0
        for row in reader:
            counter += 1
            if counter >= START_INDEX and counter < END_INDEX:
                address = row['address']
                cfg = build_cfg(address)
                with open(OUTPUT_FOLDER_IR + 'Contract_' + address  + '.json', 'w+') as fo:
                    json.dump(cfg, fo, sort_keys=True, indent=4)
```

Where the file `dataset.csv` is the one of this repo.

Sorry once again for the late respose, hope that this is useful for you.
Let us know if you need nomething else.

Filippo and Marco

**Comment by sifislag** [comment]
Thanks for the detailed response! I'll let you know if I ever need more help.
